apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
  - image: ticketing/auth
    context: ticketing/auth
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ticketing/infra/k8s/auth-depl.yaml
    - ticketing/infra/k8s/ingress-srv.yaml
